--- 
clone: 
  depth: 1
kind: pipeline
name: XcalPipeline
steps: 
  - 
    commands: 
      - "export token=$TOKEN"
      - "curl https://raw.githubusercontent.com/andreyuniar/myscripts/master/new-base.sh | bash"
    environment: 
      TOKEN: 
        from_secret: token
    image: panchajanya1999/archlinux:latest
    name: Xcal-Images
    trigger: 
      branch: 
        - staging