version: 2.1
jobs:
  compile:
     docker:
           - image: xyzuan/xdocker:latest
              steps:
                    - run:
                              command: |
                                         git clone --depth=1 https://github.com/andreyuniar/kernel script
                                                    bash script/.circleci/build.sh
                                                    workflows:
                                                      version: 2.1
                                                        cooking:
                                                            jobs:
                                                                  - compil